# Generated by Django 3.2.12 on 2022-03-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220316_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='header_image',
            new_name='image',
        ),
    ]
